### ISSUE TITLE
仕様の改善リクエスト

### ISSUE THREAD

**Issue by MergeCells** [HORIOJAPAN/arduinoserial#1]
stopで応答しなくなる問題はUNOでは発生しない模様なのでとりあえず放置で

アプリの起動後に通信可能なCOMポートの一覧を更新するボタンが欲しい
→起動後に接続したデバイスにアクセスできない（接続しなおしたときアプリの再起動が必要など）

できればdata1などの窓への数値の直打ちに対応してほしい

以上．

**Comment by Chu-son** [comment]
OneDriveにうｐし直しました
renewボタンは動くか確認してません
dataのテキストボックスは範囲外の数値が入ると何も更新しないようになっているので注意

こんなんでどうでしょう
